---
title: "preparing data"
author: "ENPRC Genomics Core"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(DropletUtils)
library(Seurat)
library(here)
knitr::opts_chunk$set(echo=FALSE,
                      warning=TRUE,
                      message=TRUE,
                      include=TRUE,
                      fig.width = 8, fig.height = 8,
                      fig.align = 'center',
                      cache=FALSE, cache.lazy = FALSE)
```

```{r}
kang.sce <- muscData::Kang18_8vs8()
kang.sce <- scater::logNormCounts(kang.sce)
kang <- Seurat::as.Seurat(kang.sce)
kang$stim <- as.character(kang$stim)
```

```{r}
for (individual in unique(kang$ind)) {
  for (cond in c('ctrl', 'stim')){
    kang.sub <- subset(kang, subset = ind == individual & stim == cond)
    DropletUtils::write10xCounts(kang.sub@assays$originalexp@counts,
                                 path = here::here(paste0("Data/kang/", 's', individual, '_', cond, '.h5')),
                                 type='HDF5', version="3", overwrite = TRUE)
  }
}
```

```{r}
for (individual in unique(kang$ind)) {
  for (cond in c('ctrl', 'stim')){
    name <- paste0(individual, '_', cond)
    obj <- Read10X_h5(here::here(paste0('Data/kang/s', name,'.h5')))
    obj <- CreateSeuratObject(obj)
    rmarkdown::render(here::here('Session-02/02-processing_template.runfile.Rmd'),
                  output_dir = here('Session-02/test_outputs'), 
                  output_file = paste0(name, '.html'))
  }
}

```

