# Getting markers for the clusters in Seurat's Guided Cluster Tutorial
library(dplyr)
library(Seurat)
library(SeuratData)
library(here)

# This is the post-processing seurat object generated by the end of the Seurat Guided Clustering Tutorial at https://satijalab.org/seurat/articles/pbmc3k_tutorial.html
InstallData("pbmc3k")

pbmc3k.final <- RenameIdents(
  pbmc3k.final,
  "Naive CD4 T" = "T_CD4_naive",
  "CD14+ Mono" = "Mono_CD14",
  "Memory CD4 T" = "T_CD4_memory",
  "B" = "B",
  "CD8 T" = "T_CD8",
  "FCGR3A+ Mono" = "Mono_FCGR3A",
  "NK" = "NK",
  "DC" = "DC",
  "Platelet" = "Platelet"
)

pbmc.markers <- FindAllMarkers(pbmc3k.final, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

pbmc.markers.top10 <- pbmc.markers %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC)

pbmc.markers.top10.list <- pbmc.markers.top10 %>%
  group_by(cluster) %>%
  group_split() %>%
  lapply(., function(x) x$gene)

unique(pbmc.markers.top10$cluster)

names(pbmc.markers.top10.list) <- unique(pbmc.markers.top10$cluster)

saveRDS(pbmc.markers.top10.list, here("04_markers+annotation/pbmc3k_markers.rds"), compress = FALSE)
